### ISSUE TITLE
Is it possible to make this work on mobile?

### ISSUE THREAD

**Issue by maawolfe36** [konodyuk/obsidian-text-expander#18]
I use Obsidian a lot on my phone and my iPad. Text Expander is really useful on PC but when I tried to install it on mobile I can't enable it after installing. Is it possible to get this working on mobile, and if so, are you able to use it without having a keyboard attached to hit the Tab key? It would be really awesome if this could use some other prompt on mobile devices since there's not a Tab key on the on-screen keyboard.

**Comment by konodyuk** [comment]
The current implementation of the plugin cannot be fully supported on mobile devices because shell commands cannot be executed there. All that remains are plain text replacements, and if you do not need any programmatic actions in your replacements, a [simpler plugin](https://github.com/ArianaKhit/text-snippets-obsidian) may be suitable for you, although I have no relation to it and cannot guarantee that it works on mobile as you expect.

To support dynamic replacements on mobile, I'll switch to js-defined scripts in `Text Expander v2`, so stay tuned.
